{
 "title": "Hidra TLS",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sample",
    "query": {
     "query": "label_values(hidra_tls_version{job=\"$job\"}, sample_name)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(hidra_tls_version, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$sample", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "sample" },
  {
   "title": "Statuses",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "hidra_sample_status{job=\"$job\", sample_name=\"$sample\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Time for certificate to expire",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hidra_tls_certificate_not_after{sample_name=\"$sample\", job=\"$job\"} - time()",
     "legendFormat": "{{host}} | {{ subject }}"
    }
   ]
  },
  {
   "title": "Handshake duration",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "hidra_tls_handshake_duration_seconds{sample_name=\"$sample\", job=\"$job\"}",
     "legendFormat": "{{host}} | {{ description }} ({{sample_name}})"
    }
   ]
  },
  {
   "title": "Certificate not after",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 13, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "hidra_tls_certificate_not_after{sample_name=\"$sample\", job=\"$job\"} * 1000",
     "legendFormat": "{{host}} | {{ subject }} | {{ description }} ({{sample_name}})"
    }
   ]
  },
  {
   "title": "Certificate not before",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 11, "x": 13, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "hidra_tls_certificate_not_before{sample_name=\"$sample\", job=\"$job\"} * 1000",
     "legendFormat": "{{host}} | {{ subject }} | {{ description }} ({{sample_name}})"
    }
   ]
  }
 ]
}