before:
  hooks:
    - go mod tidy
    - go mod vendor
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    ldflags:
      - -X github.com/hidracloud/hidra/v3/internal/misc.Version={{.Version}} -X github.com/hidracloud/hidra/v3/internal/misc.Commit={{.Commit}} -X github.com/hidracloud/hidra/v3/internal/misc.BuildDate={{.Date}} -X github.com/hidracloud/hidra/v3/internal/misc.Branch={{.Branch}}
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

nfpms:
  - id: packages
    package_name: hidra
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: "Hidra Team"
    homepage: https://hidra.cloud
    maintainer: "José Carlos <hola@josecarlos.me>"
    description: "Hidra is a tool for monitoring your services easily."
    license: "GPL-3.0"
    formats:
      - deb
      - rpm
      - apk
    dependencies:
      - chromium
    scripts:
      postinstall: ./scripts/postinstall.sh
    contents:
      - src: ./configs/hidra/exporter.yml
        dst: /etc/hidra_exporter/config.yml
        type: config|noreplace
      - src: ./configs/systemd/hidra_exporter.service
        dst: /etc/systemd/system/hidra_exporter.service
        type: config
      - src: ./configs/hidra/samples/http_test_hidracloud.yml
        dst: /etc/hidra_exporter/samples/http_demo_sample.yml.disabled
        type: config|noreplace

# furies:
#   - account: "JoseCarlosGarcia95"
#     secret_name: FURY_IO_TOKEN
publishers:
  - name: fury.io
    disable: '{{ if and .Arch (ne .Arch "amd64") }}true{{ else }}false{{ end }}'
    ids:
      - packages
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/hidracloud/
