{
 "title": "Hidra HTTP",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "client",
    "query": {
     "query": "label_values(hidra_sample_metric_status{kind=\"http\"}, client)"
    }
   },
   {
    "name": "region",
    "query": {
     "query": "label_values(hidra_sample_metric_status{kind=\"http\"}, job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(hidra_sample_metric_status{kind=\"icmp\", job=~\"$region\"}, instance)"
    }
   },
   {
    "name": "sample",
    "query": {
     "query": "label_values(hidra_sample_metric_status{kind=\"http\", client=\"$client\"}, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "UPTIME 24h",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum_over_time(hidra_sample_metric_status{kind=\"http\", client=~\"$client\",job=~\"$region\",name=~\"$sample\"}[24h])/ count_over_time(hidra_sample_metric_status{kind=\"http\", client=~\"$client\",job=~\"$region\",name=~\"$sample\"}[24h])) by (name, job)",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "APDEX",
   "type": "state-timeline",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(avg(hidra:http:apdex{client=~\"$client\",job=~\"$region\",name=~\"$sample\"}) by (name, job))",
     "legendFormat": "{{ name }} - {{ job }}"
    }
   ]
  },
  {
   "title": "HTTP Scenario statuses",
   "type": "state-timeline",
   "gridPos": { "h": 28, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(hidra_sample_metric_status{kind=\"http\", client=~\"$client\",job=~\"$region\",name=~\"$sample\"}) by (name, job)",
     "legendFormat": "{{ name }} - {{ job }}"
    }
   ]
  },
  {
   "title": "HTTP timing",
   "type": "state-timeline",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(hidra:majority:elapsed{kind=\"http\", client=~\"$client\",job=~\"$region\",name=~\"$sample\"}) by (job, name)",
     "legendFormat": "{{ name }} - {{ job }}"
    }
   ]
  },
  {
   "title": "HTTP timing",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "min(hidra:majority:elapsed{kind=\"http\", client=~\"$client\",job=~\"$region\",name=~\"$sample\"}) by (job, name)",
     "legendFormat": "{{ name }} {{ job }}"
    },
    {
     "expr": "avg(hidra:majority:elapsed{kind=\"http\", client=~\"$client\",job=~\"$region\",name=~\"$sample\"}) by (name)",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "HTTP Timing histogram",
   "type": "histogram",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 95 },
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.95, sum(rate(hidra_sample_metric_elapsed_bucket{kind=\"http\", client=~\"$client\",job=~\"$region\",name=~\"$sample\"}[5m])) by (le, name, job))) by (job, name)",
     "legendFormat": "{{ name }} - {{ job }}"
    }
   ]
  }
 ]
}