#!/bin/bash
set -e

case "$1" in
    install|upgrade)
    groupadd -r hidra
    useradd -r -g hidra -s /bin/false hidra
    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac