{
 "title": "Hidra FTP",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sample",
    "query": {
     "query": "label_values(hidra_ftp_write_time{job=\"$job\"}, sample_name)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(hidra_ftp_write_time, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$sample", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "sample" },
  {
   "title": "Statuses",
   "type": "status-history",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "hidra_sample_status{job=\"$job\", sample_name=\"$sample\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Upload speed",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "hidra_ftp_write_size{sample_name=\"$sample\", job=\"$job\"} / hidra_ftp_write_time{sample_name=\"$sample\", job=\"$job\"}",
     "legendFormat": "{{host}} | {{ description }} ({{sample_name}})"
    }
   ]
  },
  {
   "title": "Download speed",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "hidra_ftp_read_size{sample_name=\"$sample\", job=\"$job\"} / hidra_ftp_read_time{sample_name=\"$sample\", job=\"$job\"}",
     "legendFormat": "{{host}} | {{ description }} ({{sample_name}})"
    }
   ]
  }
 ]
}