{
 "title": "Hidra DNS",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sample",
    "query": {
     "query": "label_values(hidra_whois_expiration_date, sample_name)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(hidra_whois_expiration_date, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$sample", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "sample" },
  {
   "title": "Expiration date",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hidra_whois_expiration_date{sample_name=\"$sample\", job=\"$job\"} * 1000",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "Time to expiration",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hidra_whois_expiration_date{sample_name=\"$sample\", job=\"$job\"}- time()",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "Statuses",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "hidra_sample_status{job=\"$job\", sample_name=\"$sample\"}",
     "legendFormat": " "
    }
   ]
  }
 ]
}