{
 "title": "Hidra HTTP",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sample",
    "query": {
     "query": "label_values(hidra_http_response_time{job=\"$job\"}, sample_name)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(hidra_http_response_time, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$sample",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "sample",
   "collapsed": true,
   "panels": [
    {
     "title": "Statuses",
     "type": "status-history",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "hidra_sample_status{job=\"$job\", sample_name=\"$sample\"}",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Response time by time",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 13, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "hidra_http_response_dns_time{sample_name=\"$sample\", job=\"$job\"}",
       "legendFormat": "[DNS] {{method}} {{url}} | {{ description }} ({{sample_name}})"
      },
      {
       "expr": "hidra_http_response_tcp_connect_time{sample_name=\"$sample\", job=\"$job\"}",
       "legendFormat": "[TCP] {{method}} {{url}} | {{ description }} ({{sample_name}})"
      },
      {
       "expr": "hidra_http_response_tls_handshake_time{sample_name=\"$sample\", job=\"$job\"}",
       "legendFormat": "[TLS] {{method}} {{url}} | {{ description }} ({{sample_name}})"
      },
      {
       "expr": "hidra_http_response_time{sample_name=\"$sample\", job=\"$job\"} - hidra_http_response_dns_time{sample_name=\"$sample\", job=\"$job\"} - hidra_http_response_tcp_connect_time{sample_name=\"$sample\", job=\"$job\"} - hidra_http_response_tls_handshake_time{sample_name=\"$sample\", job=\"$job\"}",
       "legendFormat": "[The rest] {{method}} {{url}} | {{ description }} ({{sample_name}})"
      }
     ]
    },
    {
     "title": "Response status code by time",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 11, "x": 13, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "hidra_http_response_status_code{sample_name=\"$sample\", job=\"$job\"}",
       "legendFormat": "{{method}} {{url}} | {{ description }} ({{sample_name}})"
      }
     ]
    },
    {
     "title": "Response size by time",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 13, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "hidra_http_response_content_length{sample_name=\"$sample\", job=\"$job\"}",
       "legendFormat": "{{method}} {{url}} | {{ description }} ({{sample_name}})"
      }
     ]
    },
    {
     "title": "Download speed",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 11, "x": 13, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "hidra_http_response_content_length{sample_name=\"$sample\", job=\"$job\"} / hidra_http_response_time{sample_name=\"$sample\", job=\"$job\"}",
       "legendFormat": "{{method}} {{url}} | {{ description }} ({{sample_name}})"
      }
     ]
    }
   ]
  }
 ]
}